/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author gean3
 */
public class GestionAnimalesSearch extends javax.swing.JFrame {

    /**
     * Creates new form GestionAnimalesSearch
     */
    public GestionAnimalesSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_Especie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_Edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_HabitatID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_AnimalID = new javax.swing.JTextField();
        btn_SearchNombre = new javax.swing.JButton();
        btn_SearchEspecie = new javax.swing.JButton();
        btn_SearchEdad = new javax.swing.JButton();
        btn_SearchHabitat = new javax.swing.JButton();
        btn_SearchAnimalID = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        btn_SearchHabitatType = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_HabitatIType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Zoologico Internacional - Gestion de animales [Modificar]");
        jLabel1.setName("lvl_ZoologicoInternacional"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Buscar por:");

        tf_Nombre.setToolTipText("");

        jLabel4.setText("Especie:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Habitat ID:");

        jLabel2.setText("Nombre:");

        jLabel7.setText("Animal ID:");

        btn_SearchNombre.setText("Buscar");
        btn_SearchNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchNombreActionPerformed(evt);
            }
        });

        btn_SearchEspecie.setText("Buscar");
        btn_SearchEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchEspecieActionPerformed(evt);
            }
        });

        btn_SearchEdad.setText("Buscar");
        btn_SearchEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchEdadActionPerformed(evt);
            }
        });

        btn_SearchHabitat.setText("Buscar");
        btn_SearchHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchHabitatActionPerformed(evt);
            }
        });

        btn_SearchAnimalID.setText("Buscar");
        btn_SearchAnimalID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchAnimalIDActionPerformed(evt);
            }
        });

        btn_Back.setText("Volver");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_SearchHabitatType.setText("Buscar");
        btn_SearchHabitatType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchHabitatTypeActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre del habitat:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(tf_Nombre)
                            .addComponent(jLabel4)
                            .addComponent(tf_Especie)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_SearchEdad))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_AnimalID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_SearchAnimalID))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_HabitatID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_SearchHabitat)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_HabitatIType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_SearchNombre)
                                    .addComponent(btn_SearchEspecie)
                                    .addComponent(btn_SearchHabitatType)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btn_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchNombre))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchEspecie))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchEdad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_HabitatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SearchHabitat)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_HabitatIType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SearchHabitatType))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_AnimalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SearchAnimalID)
                    .addComponent(btn_Back))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        GestionHabitats menu = new GestionHabitats();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_SearchNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchNombreActionPerformed
        // TODO add your handling code here:
        String Searching = tf_Nombre.getText();
        int Type = 1;
        Data.AnimalesDataSearch(Searching,Type);
    }//GEN-LAST:event_btn_SearchNombreActionPerformed

    private void btn_SearchEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchEspecieActionPerformed
        // TODO add your handling code here:
        String Searching = tf_Especie.getText();
        int Type = 2;
        Data.AnimalesDataSearch(Searching,Type);
    }//GEN-LAST:event_btn_SearchEspecieActionPerformed

    private void btn_SearchEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchEdadActionPerformed
        // TODO add your handling code here:
        String Searching = tf_Edad.getText();
        int Type = 3;
        Data.AnimalesDataSearch(Searching,Type);
    }//GEN-LAST:event_btn_SearchEdadActionPerformed

    private void btn_SearchHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchHabitatActionPerformed
        // TODO add your handling code here:
        String Searching = tf_HabitatID.getText();
        int Type = 5;
        Data.AnimalesDataSearch(Searching,Type);
    }//GEN-LAST:event_btn_SearchHabitatActionPerformed

    private void btn_SearchHabitatTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchHabitatTypeActionPerformed
        // TODO add your handling code here:
        String Searching = tf_HabitatIType.getText();
        int Type = 4;
        Data.AnimalesDataSearch(Searching,Type);
    }//GEN-LAST:event_btn_SearchHabitatTypeActionPerformed

    private void btn_SearchAnimalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchAnimalIDActionPerformed
        // TODO add your handling code here:
        String Searching = tf_AnimalID.getText();
        int Type = 6;
        Data.AnimalesDataSearch(Searching,Type);
    }//GEN-LAST:event_btn_SearchAnimalIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAnimalesSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAnimalesSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAnimalesSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAnimalesSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAnimalesSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_SearchAnimalID;
    private javax.swing.JButton btn_SearchEdad;
    private javax.swing.JButton btn_SearchEspecie;
    private javax.swing.JButton btn_SearchHabitat;
    private javax.swing.JButton btn_SearchHabitatType;
    private javax.swing.JButton btn_SearchNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf_AnimalID;
    private javax.swing.JTextField tf_Edad;
    private javax.swing.JTextField tf_Especie;
    private javax.swing.JTextField tf_HabitatID;
    private javax.swing.JTextField tf_HabitatIType;
    private javax.swing.JTextField tf_Nombre;
    // End of variables declaration//GEN-END:variables
}
